version: '3.4'

services:
  customer:
    image: customer
    build:
      context: .
      dockerfile: ./microservices/customer/Dockerfile
    environment:
        NODE_ENV: production
        CLOUDAMQP_URL: amqps://knonqsms:xhCosYXBsyLlHLadSlcUyzgfIz53B9AJ@rattlesnake.rmq.cloudamqp.com/knonqsms
        PORT: 3001
    ports:
        - 3001:3001
    expose:
        - 3001

  order:
    image: order
    build:
      context: .
      dockerfile: ./microservices/order/Dockerfile
    environment:
        NODE_ENV: production
        CLOUDAMQP_URL: amqps://knonqsms:xhCosYXBsyLlHLadSlcUyzgfIz53B9AJ@rattlesnake.rmq.cloudamqp.com/knonqsms
        PORT: 3002
    ports:
        - 3002:3002
    expose:
        - 3002

  product:
    image: product
    build:
      context: .
      dockerfile: ./microservices/product/Dockerfile
    environment:
        NODE_ENV: production
        CLOUDAMQP_URL: amqps://knonqsms:xhCosYXBsyLlHLadSlcUyzgfIz53B9AJ@rattlesnake.rmq.cloudamqp.com/knonqsms
        PORT: 3003
    ports:
        - 3003:3003
    expose:
        - 3003
